### ISSUE TITLE
Feature: bigger sticker preview

### ISSUE THREAD

**Issue by suraj3486** [FredHappyface/Android.EweSticker#10]
Please add one feature in which it should show a larger preview of selected sticker before sending.
With a button in bottom send. It will help stickers with text in it.

**Comment by FredHappyface** [comment]
Unfortunately, the sticker preview is handled by the application input and not by EweSticker so there's nothing I can do about it at present. One option may be to increase the sticker size in the keyboard

**Comment by suraj3486** [comment]
https://user-images.githubusercontent.com/54233248/137950905-d46ab49f-0f64-4f1b-908b-47eb6101998c.mp4

It is short example this is how it will be useful

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FredHappyface/Android.EweSticker/commit/0faee9546a4b010290069ef4d8d734cb0453fbd8
