### ISSUE TITLE
Feature: edit number of row in vertical scroll

### ISSUE THREAD

**Issue by suraj3486** [FredHappyface/Android.EweSticker#16]
After choosing vertical scrolling i m not able to edit row and dp.
But horizontally it is possible
![Screenshot_20211030-085208753](https://user-images.githubusercontent.com/54233248/139518774-86d828c4-977a-4443-8a26-be2d238735fa.jpg)

**Comment by FredHappyface** [comment]
Disabling the ability to change the sticker size is intended behaviour

Though thinking on it, being able to change the number of columns is probably a good idea

**Comment by FredHappyface** [comment]
Just a note for future whilst in thinking on it. Please fill in the template properly for issues - given the time I spend on this providing free software support its really the least you can do. Thanks ☺️
