### ISSUE TITLE
Feature: Accept nested directory structure

### ISSUE THREAD

**Issue by Millesimus** [FredHappyface/Android.EweSticker#17]
First of all, I really love what you are doing here. I always hoped for a keyboard where I could just add all the stickers I want. :3

## Feature
- [x] I have read the comment above and have completed each step
- [x] I have filled in each heading below

### Is your feature request related to a problem? Please describe
My sticker collection is currently sorted in categories, like 
```
sticker-root/animals/"Just Zoo It"
sticker-root/animals/"Zozo the French Bulldog"
```
EweSticker does not find these (as is described in the tutorial).

I would like to keep my stickers sorted in categories.

### Describe the solution you'd like
All stickers from subdirectories should be shown in the keyboard. The last folder in the hierarchy denotes the pack name.

Optionally, if the keyboard could display these categories (100+ packs are too many for vertical scrolling…).

### Describe alternatives you've considered
Sorting all subdirectories in one root-folder according to the tutorial and curate my sticker pack collection / sort a lot of packs out. But that would be sad.

**Comment by FredHappyface** [comment]
Sounds like a useful feature. I'll look at adding this in the next version

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FredHappyface/Android.EweSticker/commit/3a5759ff340834144504f95c9f6eb2db8eadfb23
