### ISSUE TITLE
Feature: sticker search in keyboard

### ISSUE THREAD

**Issue by suraj3486** [FredHappyface/Android.EweSticker#19]
Is it possible to add search option like 'Gboard sticker search' which will search stickers locally?
Finding stickers according to name would be awesome feature.

**Comment by FredHappyface** [comment]
Fill in the template please

**Comment by FredHappyface** [comment]
Also please see https://github.com/rzhou1999/woosticker/issues/4#issuecomment-817251269

**Comment by singpolyma** [comment]
I guess gboard can do this because they already *are* a full letter keyboard also?

**Comment by FredHappyface** [comment]
Yeah pretty much, it'd just be too much work to get this feature in. There's loads of stuff is like to do with this app but time always becomes the limiting factor here

**Comment by FredHappyface** [comment]
Got there in the end :) 

https://github.com/FredHappyface/Android.EweSticker/releases/tag/20240322
