### ISSUE TITLE
Bug: No image appears on the keyboard

### ISSUE THREAD

**Issue by juacq97** [FredHappyface/Android.EweSticker#22]
## Bug
- [x] I have read the comment above and have completed each step
- [x] I have filled out the system info
- [x] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### System info

- OS: Lineage OS 18.1, Android 11
- Version: 2021.10.21

### Describe the bug
I added some png and jpg files to a folder and selected that folder in the app. When I open the keyboard, nothing appears.

### Expected outcome
The images on the folder appears 

### Actual outcome
Nothing appears

### Photos:

![Screenshot_20211103-114123_Archivos](https://user-images.githubusercontent.com/7623047/140174210-9ea1ecdb-a76d-46d2-9d25-30bb9eeb476d.png)
![Screenshot_20211103-114134_Archivos](https://user-images.githubusercontent.com/7623047/140174211-920cecdd-4833-40a7-bd72-1ffaa273b623.png)
![Screenshot_20211103-114145_EweSticker](https://user-images.githubusercontent.com/7623047/140174215-efbc030d-aa2d-4299-8e0c-4e82c1570b6e.png)
![Screenshot_20211103-114227_Trebuchet](https://user-images.githubusercontent.com/7623047/140174217-400af51d-f9f0-4c0b-a041-c7ca8900a89a.png)

**Comment by FredHappyface** [comment]
Hi thanks for opening the issue 😊

Looks like some failure in identifying the image mimetype. Would it be possible to attach a couple to the issue and I'll see if I can duplicate this?

Can you also confirm that total remains at 0 after importing the stickers?

**Comment by juacq97** [comment]
ok, it seems to be solved, I deleted the app data and selected the folder again. Now it's working

**Comment by FredHappyface** [comment]
Glad you got it working in the end ☺️
