### ISSUE TITLE
Feature: switching back to previous keyboard

### ISSUE THREAD

**Issue by suraj3486** [FredHappyface/Android.EweSticker#23]
I love this app that is why i keep on suggesting features and thanx to developer for keep on allowing me to do so..

## Feature
- [ ✓] I have read the comment above and have completed each step
- [ ✓] I have filled in each heading below

### Is your feature request related to a problem? Please describe
It is an enhancement compared to the existing feature.

### Describe the solution you'd like
on soft click of back button it should bring back to previous used keyboard and on long press it should ask for keyboard in popup.

### Describe alternatives you've considered
implementation of this feature will be really useful and time saving.
Right now on clicking back it directly ask for keyboard which should be there on long press of back button and on soft click it should automatically change back to previously used keyboard.

### Additional context
and please change back button icon to something nice like some good keyboard icon or something.
And thank you for this app.
![Screenshot_20211107-161745685](https://user-images.githubusercontent.com/54233248/140655901-ba9486fe-76f2-4507-9842-9f4be282118b.jpg)

**Comment by FredHappyface** [comment]
Hi thanks for the issue

Sadly looks like this isn't possible as apps are not created equal on Android. Many things Google apps can do are simply not an option for the average Dev

https://stackoverflow.com/questions/11036435/switch-keyboard-profile-programmatically

https://stackoverflow.com/questions/29783043/how-to-programmatically-switch-between-the-phones-keyboards

This is a feature that I'd have liked to have seen myself but reading the above it's looking like a wont-fix

Thanks again 🙂

**Comment by suraj3486** [comment]
I have seen many keyboards have this feature which are not made by Google like
https://play.google.com/store/apps/details?id=com.highstarapp.pastekeyboard

https://play.google.com/store/apps/details?id=com.uberfables.leface.keyboard

Etc

**Comment by FredHappyface** [comment]
I'll take another look. Thanks

**Comment by suraj3486** [comment]
And also please change ' changing keyboard icon ' ...

**Comment by FredHappyface** [comment]
Thanks for persisting :P - Turns out this was possible after all! Fixed in https://github.com/FredHappyface/Android.EweSticker/commit/877947a57c901ce7fcb518d42321faadba2d4ffc 

Following from this I'd argue the icon is very appropriate but by all means suggest an alternative if you have one you prefer

**Comment by suraj3486** [comment]
![Screenshot_20211110-070142183](https://user-images.githubusercontent.com/54233248/141033255-b898a2de-caa2-4a8d-95ce-804350d64f98.jpg)
 This icon is the universal one.

**Comment by FredHappyface** [comment]
Looks like there's some inconsistency between icons on the main OS'

See 
- https://support.swiftkey.com/hc/en-us/articles/201591521-How-do-I-switch-between-and-manage-my-keyboards-
- https://support.apple.com/en-gb/guide/iphone/iph73b71eb/ios
- https://support.microsoft.com/en-us/windows/change-your-keyboard-layout-245c49b8-f856-7fd7-2cf5-41e54c66f5b3

Looks like the keyboard type icon is the most common. However this seems to open some picker. The icon you've suggested seems to be very iOS inspired and so I'm not sure is completely appropriate. Given that the back icon now means back I'm going to keep it for the time being. However, had I not implemented that functionality I'd have likely have switched to the keyboard icon 

Cheers 🙂

**Comment by suraj3486** [comment]
🍻 no problem
