### ISSUE TITLE
Bug: stickers are not visible clearly

### ISSUE THREAD

**Issue by suraj3486** [FredHappyface/Android.EweSticker#24]
Thanks for the update, i m using latest update (14112021)

## Bug
- [ ✓ ] I have read the comment above and have completed each step
- [ ✓ ] I have filled out the system info
- [ ✓ ] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### System info

- OS: Android 11
- Browser: Chrome, 1dm+
- Version: latest from Play Store
![Screenshot_20211115-115932276](https://user-images.githubusercontent.com/54233248/141741789-c81fe15b-b09e-41b5-9ac4-6f8b9eb6b1c8.jpg)
![Screenshot_20211115-115914982](https://user-images.githubusercontent.com/54233248/141741816-4fc378ae-c75e-4d18-830e-98af338bc270.jpg)

### Describe the bug
In vertical scroll stickers are not visible clearly last row stickers are little outside of the screen.
As u can see in preview after changing rows problem still persist.

### Expected outcome
It should be clearly within the screen after changing to vertical scroll and rows

**Comment by FredHappyface** [comment]
Thanks for raising this - I've been able to reproduce this on my own device. I'll take a look at this
