### ISSUE TITLE
Feature: maximise larger preview

### ISSUE THREAD

**Issue by suraj3486** [FredHappyface/Android.EweSticker#25]
Thanks for the latest update i m using (20211114) version

## Feature
- [ ✓ ] I have read the comment above and have completed each step
- [ ✓ ] I have filled in each heading below

### Is your feature request related to a problem? Please describe
Is it possible to maximise long press sticker preview?

### Describe the solution you'd like
Please remove that note in larger preview and enlarge the preview to maximum extent.

### Describe alternatives you've considered
If not possible no problem existing feature is also good.

### Additional context
Bigger preview will be helpful for stickers containing text in it
![Screenshot_20211114-224352166](https://user-images.githubusercontent.com/54233248/141744383-adb93634-fd24-4923-a8b0-e0bac1ce9a32.jpg)

**Comment by FredHappyface** [comment]
Hi thanks for the issue - I'll take a look at improving this. One issue I encountered in testing was the text being covered when the image was too large so I'll investigate this
