### ISSUE TITLE
Bug: changing icon size in vertical scroll

### ISSUE THREAD

**Issue by suraj3486** [FredHappyface/Android.EweSticker#26]
Thanks for the update i m using latest version

## Bug
- [ ✓ ] I have read the comment above and have completed each step
- [ ✓ ] I have filled out the system info
- [ ✓ ] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### System info

- OS: Android 11
- Browser: 1dm+, Chrome
- Version: latest available on Play Store

### Describe the bug
Not able to edit icon size in latest update

### Expected outcome
In horizontal scrolling it possible to edit icon size please make it available in vertical scroll.
![Screenshot_20211115-133553386](https://user-images.githubusercontent.com/54233248/141745925-3e3f657b-77a7-48fd-975d-558c4d4d081b.jpg)

**Comment by FredHappyface** [comment]
Hi thanks for the issue. This is intended behavior - as the width is determines by the number of columns and the keyboard width
