### ISSUE TITLE
Feature: please, don't include the apk in the github repo

### ISSUE THREAD

**Issue by adbenitez** [FredHappyface/Android.EweSticker#27]
## Feature
- [X] I have read the comment above and have completed each step
- [X] I have filled in each heading below

### Is your feature request related to a problem? Please describe
The repo size will grow each time you update the apk file, previous apks are kept in the git history.

### Describe the solution you'd like
remove the apk file from the repo, they are available anyway in the releases page, the "direct apk download" button in the README should link to the releases pages or to the direct download link in the releases

### Additional context
some people like me (Cuban) only have expensive mobile data plan and it will be a hassle if someone like me would like to contribute, because the full repo needs to be cloned and updated each time you upload an updated version of the apk file.

**Comment by FredHappyface** [comment]
Thanks, seems like a reasonable request - the inclusion of the apk comes from wanting to distribute a binary before using the github releases feature

**Comment by FredHappyface** [comment]
Fixed - be sure to use the releases page if you want to download the apk
