### ISSUE TITLE
Feature: support older Android versions

### ISSUE THREAD

**Issue by adbenitez** [FredHappyface/Android.EweSticker#28]
## Feature
- [X] I have read the comment above and have completed each step
- [X] I have filled in each heading below

### Is your feature request related to a problem? Please describe
I'm recommending EweSticker to users and several users have Android<8  

### Describe the solution you'd like
The app can be used at least in Android 5

### Describe alternatives you've considered
Some user did a modification to the app with this apks that allow to quickly patch other apps in your phone, and some report to be able to use this mod in older Androids

### Additional context
I am recommending this app to Delta Chat users, Delta Chat is a FLOSS messenger app and it has sticker support but still don't have a built-in sticker selector so EweSticker + DeltaChat is a nice symbiosis, issue is that Delta Chat supports up to Android 4.1, and EweSticker only up to Android 8, so a good part of the user base can't use EweSticker.

More info about Delta Chat: https://github.com/deltachat/deltachat-android and https://delta.chat/

**Comment by adbenitez** [comment]
btw, this is how stickers send with EweSticker looks in Delta Chat:

![Screenshot_20211118-132609_DeltaLab](https://user-images.githubusercontent.com/24558636/142475545-5895e1a1-d840-47aa-aa4c-abe448bebc9d.jpg)

thanks for the great work!

**Comment by FredHappyface** [comment]
In my testing the app requires extra work to support older versions and few people (worldwide) seem to use older that api 26 (13% according to https://apilevels.com/) 

![image](https://user-images.githubusercontent.com/41634689/142507189-75a0fdd1-eb14-4df7-ba22-681ed56c250e.png)

You're welcome to open a merge request for this providing that this can be done without adding loads to the codebase. But this looks like a lot of work and therefore time that I do not have so going to mark this wontfix 

Thanks for the issue :)

**Comment by adbenitez** [comment]
it is bigger than 13% not everyone uses Google Play etc. still 13% of the world is a big part ;)
I will play with this when I manage to download deps etc. and can compile the app

**Comment by FredHappyface** [comment]
Sounds good! Looks like it's going to be a lot of work as the sticker import uses methods that require API 26+
