### ISSUE TITLE
Feature: mark current selected tab

### ISSUE THREAD

**Issue by adbenitez** [FredHappyface/Android.EweSticker#29]
## Feature
- [X] I have read the comment above and have completed each step
- [X] I have filled in each heading below

### Is your feature request related to a problem? Please describe
there is no visual feedback of what is the selected sticker pack in the tab icons.

### Describe the solution you'd like
usually the tab would be underlined, so I recommend to underline the selected tab.

**Comment by FredHappyface** [comment]
I took a look at this and honestly can't work out how to do this easily, if you have any ideas then you can open a merge request or drop a reply and I'd be happy to include it as I agree that it would be a good QOL feature
