### ISSUE TITLE
Bug: "Recent" tab not saved as last used tab

### ISSUE THREAD

**Issue by adbenitez** [FredHappyface/Android.EweSticker#30]
## Bug
- [X] I have read the comment above and have completed each step
- [X] I have filled out the system info
- [X] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### System info

- OS: Android 11
- Version: EweSticker 2021.11.14

### Describe the bug
I select the "Recent" tab, select an sticker then go back to my keyboard, when I go back to EweSticker again, the selected tab is not the "Recent" tab but another tab I selected before selecting the Recent tab

### Expected outcome
The Recent tab is preserved as the last selected tab when I go back to my keyboard

### Actual outcome
The tab selected before selecting the Recent tab is the one selected when you go back to EweSticker

**Comment by FredHappyface** [comment]
Hi thanks for the report - good spot 

I'll have a look at this sometime but I would say it's reasonably low priority tbh

**Comment by FredHappyface** [comment]
Fixed in 20211118 - turned out to be a remarkably easy fix :D
