### ISSUE TITLE
Feature: Request the user to enable EweSticker input method

### ISSUE THREAD

**Issue by adbenitez** [FredHappyface/Android.EweSticker#31]
## Feature
- [X] I have read the comment above and have completed each step
- [X] I have filled in each heading below

### Is your feature request related to a problem? Please describe
It is not obvious to the user that they have to enable the EweSticker input method in the phone settings, the first time I tried I was confused about how do I use EweSticker, usually keyboards when you install them and open them for the first time, ask to enable the input method and open the correct settings directly.

### Describe the solution you'd like
the app ask me to enable EweSticker input method and make it easy to do so opening the corresponding system settings

### Additional context
maybe you can check the code of AnySoftKeyboard or OpenBoard to see how they do it.

**Comment by FredHappyface** [comment]
The app provides a link to a tutorial which explains this https://github.com/FredHappyface/Android.EweSticker/blob/main/TUTORIAL.md#step-4---activate-the-keyboard

I'd always encourage users to spend a few minutes to read this. Given the learning + dev time to add this I'm probably going to mark this wontfix. Though again, you are welcome to look into this if you want to

**Comment by adbenitez** [comment]
> The app provides a link to a tutorial which explains this

I didn't see the tutorial link in the app, now I checked, it is too distant from the "How to Use" section, it is at the end, below even the license an copyright notice, in the Links section in the middle of other two longs links and it is easy to oversee in a section that is more like a "About" section, 

I recommend to move the tutorial link to the "How to Use" section that is where users would expect to find a tutorial ;)

**Comment by adbenitez** [comment]
> Though again, you are welcome to look into this if you want to

I might look into it if I find some time, but I am a bit busy already and also I am not used to Kotlin, also right now I can't compile the apk myself because fetching the dependencies from maven will cost me a good part of my data plan, so I have to plan when I can do this

**Comment by FredHappyface** [comment]
Looks like this can be achieved fairly simply:
- https://developer.android.com/guide/components/intents-common
- https://developer.android.com/reference/android/provider/Settings#ACTION_INPUT_METHOD_SETTINGS

Happy to take a look in more detail though I likely wont release an update until December now

**Comment by FredHappyface** [comment]
Just a note that I have not forgotten this issue! I'll have a proper look by the 25th December (probably over the next week or so)

**Comment by FredHappyface** [comment]
Fixed
