### ISSUE TITLE
Feature: switch between folders by swiping

### ISSUE THREAD

**Issue by suraj3486** [FredHappyface/Android.EweSticker#33]
Thank you for this app, i really like this application. I like to request one feature which will improve its functionality.

## Feature
- [ ✓ ] I have read the comment above and have completed each step
- [ ✓ ] I have filled in each heading below

### Describe the solution you'd like
I usually use vertical scroll.
Please add swipe in folder which will change folder to next or previous like shown in pic.

### Additional context
It will make keyboard litte easy to use.
![Screenshot_20211119-113607469](https://user-images.githubusercontent.com/54233248/142574993-26b882da-00c9-47ac-8faa-a6e39643eb18.jpg)

**Comment by FredHappyface** [comment]
Hi thanks for the feature request. As this wouldn't work with horizontal scroll I'm going to mark this as wontfix

**Comment by suraj3486** [comment]
In horizontal scrolling swiping vertical is a good idea

**Comment by FredHappyface** [comment]
I guess I'm asking what problem does this solve for you? Is this more of a quality of life thing or is the current selection method causing issues for you?

**Comment by FredHappyface** [comment]
Upon reflection I'd like to reopen this issue as it may be worth further investigation. Though at this time it is fairly low priority for me to implement this
