### ISSUE TITLE
Feature: add animated fallback for use in apps not supporting webp

### ISSUE THREAD

**Issue by suraj3486** [FredHappyface/Android.EweSticker#36]
[02200004.zip](https://github.com/FredHappyface/Android.EweSticker/files/7950812/02200004.zip)
I m using latest app from github.

## Bug

- [ ✓ ] I have read the comment above and have completed each step
- [ ✓ ] I have filled out the system info
- [ ✓ ] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### System info

- OS: Android 11
- Browser: chrome, 1dm+
- Version: latest from playstore

### Describe the bug
When i try to use stickers which is webp format than it got uploaded like jpg without animation.

### Expected outcome
It should animate as like opening it in any gallery viewer

### Actual outcome
It didn't animate it just pasted as jpg or png sticker.

**Comment by FredHappyface** [comment]
Hi thanks for your report 

What app are you using? As you may be aware, EweSticker uses webp as a fall-back if the app input field doesn't support webp. Frustratingly, most apps do not support webp or seem to handle it in an undesirable manner. For many of these your best bet is to contact support for each app as the best I can do is fall-back to some (hopefully) supported format which is png as most things support that (though not the search bar in google chrome). Alternatively use something like gif instead 


|app|id|webp|animated?|notes|
|---|---|---|---|---|
|Android Messages|com.google.android.apps.messaging|:x:|:x:||
|WhatsApp|com.whatsapp| :x:| :x:|Supports image/webp.wasticker|
|Telegram|org.telegram.messenger|✅|:x:|Supports image/webp but for some reason will not animate|
|Signal|org.thoughtcrime.securesms|:x:|:x:||
|Discord|com.discord|✅|✅||


Just a note on the app version, that's made pretty clear on the releases page on github if you've got it from there, f-droid does a good job of telling you. If downloaded from google play you should be able to head to about app on the store page 

Also, don't worry about filling out your browser version unless you want to 😉

Hope this has answered your question and apologies that I cannot offer a magic fix for this one - this is an issue I personally find immensely frustrating

**Comment by FredHappyface** [comment]
Link to bugtrackers 


- Android Messages TODO
- WhatsApp TODO
- Telegram https://bugs.telegram.org/c/16789 / https://bugs.telegram.org/c/1621 (animated WebP support)
- Signal TODO

**Comment by FredHappyface** [comment]
Further investigation into this shows that it may be possible via imagemagick. However, this is a lot of work/ learning and may reduce the app stabilty (something recent commits have looked to improve). If this is a feature you want to see then please add a thumbs up. If this gets no traction then I'll close

**Comment by FredHappyface** [comment]
Many hours later and this absolutely is not feasible

I ended up using the kmagic library that wraps imagemagick. This functionality was possible to achieve but took around 5 to 10 seconds to encode to gif 

Not sure why as this seems rather long. Finally going to close this one as wontfix as I cannot justify spending more time than I have on this (next step would be hoping that driving imagemagick more directly would be different)
