### ISSUE TITLE
Feature: implement max sticker size

### ISSUE THREAD

**Issue by FredHappyface** [FredHappyface/Android.EweSticker#42]
## Feature

- [x] I have read the comment above and have completed each step
- [x] I have filled in each heading below

### Is your feature request related to a problem? Please describe

Improving application stability (+ sticker copy speed)

### Describe the solution you'd like

It's probably a good idea to exclude massive images as these would not constitute a sticker. This issue is to consider the max image size in bytes for a future version 

For instance the largest photo taken on my camera is approximately 7MB - and certainly would make a terrible sticker 

For existing applications the limits are as follows 

|app|id|max size (KB)|source|
|---|---|---|---|
|WhatsApp|com.whatsapp|100|https://faq.whatsapp.com/general/how-to-create-stickers-for-whatsapp/?lang=en|
|Telegram|org.telegram.messenger|512|https://core.telegram.org/import-stickers|
|Signal|org.thoughtcrime.securesms|300|https://support.signal.org/hc/en-us/articles/360031836512-Stickers|

Maximum sized gif in some tstickers (https://github.com/FHPythonUtils/TStickers) output was <2MB and the largest webp was approximately 1.6MB so going to propose 2MB (Already far larger than existing applications use by about 4x)

Also, if the user had 4096 stickers at this size (the current limit), then they could have 8GB in stickers 

### Describe alternatives you've considered

Could do nothing but this could cause ewesticker to consume too many resources and affect the application stability (e.g. when loading 128 massive image files into the keyboard)

Other options involve trying to get the sticker dimensions but I suspect this is going to be difficult with DocumentFile

Or sum the sticker sizes and abort at some max size e.g. 2GB (so a user can still use a handful of massive files if desired) perhaps even combining these ideas 

### Additional context

This is an issue rather than a discussion as I plan on working on this in the next development cycle (1-2 months) . Comments are welcome

**Comment by mpfaff** [comment]
If you implement a limit, use whatever default you want, but make it configurable in the app.

**Comment by FredHappyface** [comment]
Tbh this is unlikely to make it in anytime soon but I'll definitely take that into consideration, thanks 😊

**Comment by FredHappyface** [comment]
I think this would be for it's own sake and I'm not convinced this would have much bearing on application stability etc. So closing
