### ISSUE TITLE
Feature: Telegram sticker file support

### ISSUE THREAD

**Issue by karmakarmeghdip** [FredHappyface/Android.EweSticker#45]
So basically I like to export animated stickers in telegram that I collect and use them in Delta Chat.

The animated stickers are usually in .tgs file format which eweSticker doesn't support.

So I have to convert them to gifs which is choppier and much lower quality compared to the original. 

So please, .tgs support would be appreciated!!

**Comment by FredHappyface** [comment]
Hi thanks for opening the issue and apologies for the delayed response (it has been a busy couple months!)

EweSticker is not able to render .tgs as we use coil https://coil-kt.github.io/coil/ to do the heavy lifting. Also whilst .tgs is based on open standards its not exactly easy or all that quick to transform .tgs to other formats like .gif, unfortunately. (I've had a stab at creating Python wrappers of two popular implementations at https://github.com/FHPythonUtils?q=lottie&type=all&language=&sort=, the good news is that you may be able to convert - plus they provide additional options for 'quality' vs 'performance')

So sadly this is way out of scope at present. Though PRs are very welcome if you've a good idea/ prototype on how to solve this 

Sorry - going to have to mark this as wontfix for now 

Though feel free to reopen if needed :)
