### ISSUE TITLE
Bug: Have to change the sticker directory for it to find new stickers

### ISSUE THREAD

**Issue by singpolyma** [FredHappyface/Android.EweSticker#46]
## Bug

- [x] I have read the comment above and have completed each step
- [x] I have filled out the system info
- [x] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### System info

- OS: Emulator, android 11
- Version: 2022.03.11

### Describe the bug

When I add new pictures to the stickers folder they do not show up right away

### Expected outcome

I should see them in the keyboard when I open it, the app should list the right count of stickers

### Actual outcome

The new images don't show up until I change the sticker folder (I can set it to what it is already set to, but I still have to do it)

**Comment by FredHappyface** [comment]
There's some partial success with this. Due to how its been implemented previously, we copy stickers to app storage as this makes the app more performant. I've gone ahead and added a refresh button which will reimport your stickers without the need to browse for them
