### ISSUE TITLE
Feature: Support import from tar file

### ISSUE THREAD

**Issue by singpolyma** [FredHappyface/Android.EweSticker#47]
## Feature

- [x] I have read the comment above and have completed each step
- [x] I have filled in each heading below

### Is your feature request related to a problem? Please describe

Want a way to share sticker packs and make them easy for others to install.

### Describe the solution you'd like

Associate the app with `application/x-tar` and when triggered unpack the archive and install all stickers/packs inside into the current sticker directory.

### Describe alternatives you've considered

* A custom URI scheme that could be linked from a webpage to trigger the download

**Comment by FredHappyface** [comment]
Hi I've had a look at this and it's currently out of scope for the app. The best option would be to manually extract the tarfile to a location on your device and use the sticker import function 

Thanks for the idea though! :)
