### ISSUE TITLE
Feature: Add support for wechat

### ISSUE THREAD

**Issue by UNTRIVAL** [FredHappyface/Android.EweSticker#48]
## Feature

- [x] I have read the comment above and have completed each step
- [x] I have filled in each heading below

### Is your feature request related to a problem? Please describe

I can't send stickers in wechat.

### Describe the solution you'd like

This app currently cannot send stickers in wechat, but gboard can send stickers in the way of system sharesheets.

![Screenshot_20230417_134705_Android System](https://user-images.githubusercontent.com/108966196/232393974-ff257141-e620-42e3-8dbb-c881279b851e.jpg)

### Describe alternatives you've considered

Use the same method of gboard to send stickers in other apps with similar situations?

### Additional context

Samsung keyboard is similar to the gboard.

![Screenshot_20230417_135504_Android System](https://user-images.githubusercontent.com/108966196/232395323-2d1ba201-a7e7-4018-ba98-0cdb34c84530.jpg)

**Comment by FredHappyface** [comment]
Hi finally got around to implementing this :) 

Will be available in the next update
