### ISSUE TITLE
Feature: Version name/number/date in app

### ISSUE THREAD

**Issue by virginviolet** [FredHappyface/Android.EweSticker#72]
## Feature Details

Which version of the Ewe Sticker app you are running should be displayed somewhere in the app.

### Is your feature request related to a problem? Please describe

I looked in the app first to find out which version I had when issuing a bug report, but didn't find it. Many users might not know where to find this information, and will look in the app first, and they might get frustrated in not finding it. 
Adding the version name in the app somewhere would make bug reports less painful for people. Some other apps, like Anki, has this feature. Most PC programs do.

### Describe the solution you'd like

Render the version name somewhere in the app.  Perhaps under "Info".

### Describe alternatives you've considered

You could just let users find out the version number in other ways, like through settings.

**Comment by FredHappyface** [comment]
Thanks for this :) 

Fixed in https://github.com/FredHappyface/Android.EweSticker/tree/20240825
