### ISSUE TITLE
Feature: sort stickers according to name, date, size

### ISSUE THREAD

**Issue by suraj3486** [FredHappyface/Android.EweSticker#9]
Please add a option for shortlisted file according to name, date, size etc..
Please add a switch in keyboard topbar so that it can be changed within the keyboard.

**Comment by FredHappyface** [comment]
I'll take a look at this. FYI stickers are currently sorted by name 

Can you provide an example of how you might use this so I can get a better idea of how to implement this? 

Thanks

**Comment by FredHappyface** [comment]
Going to mark this as wont-fix due to limited Dev time and no clear use case for this feature
